In [3]:
import pandas as pd
df=pd.read_csv(r'/Users/mohamadnayal/Documents/Syracuse/Summer_2021/IST_652/assignments/Hw2/version2/Final_comment_stats.csv')
display(df.head())

,id,comment_display,comment_text,like_count,comment_publish_date,comment_up_date,reply_count,text_length,comment_time,comment_hr,time_cat
0,UgzCnmv8bCXdxnkJUGN4AaABAg,Dude perfect is the perfect example of quality...,Dude perfect is the perfect example of quality...,0,2021-08-24 18:25:22+00:00,2021-08-24T18:25:22Z,0.0,60,18:25:22,18,night
1,Ugxby2VEQoLXFaKwXJ54AaABAg,Coby the only one who always lost the finally ...,Coby the only one who always lost the finally ...,0,2021-08-25 05:21:51+00:00,2021-08-25T05:21:51Z,0.0,55,05:21:51,5,late night
2,UgxzSjiqDtvvABYfgSt4AaABAg,"next time, can you pls put stereotypes, i am d...","next time, can you pls put stereotypes, i am d...",1,2021-08-25 02:09:32+00:00,2021-08-25T02:09:32Z,0.0,60,02:09:32,2,late night
3,Ugz1GxO3BZOhbUK657t4AaABAg,I like how they are using ty’s water scooter f...,I like how they are using ty’s water scooter f...,14,2021-08-23 23:07:12+00:00,2021-08-23T23:07:12Z,1.0,61,23:07:12,23,night
4,Ugz0kDoAn1-fEkvMwMh4AaABAg,This is exactly what we needed!,This is exactly what we needed!,1,2021-08-24 15:05:58+00:00,2021-08-24T15:05:58Z,1.0,31,15:05:58,15,working hours